apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: charlesd-sorn-fig2-py2-storage
  namespace: hengenlab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 20Gi
